### ISSUE TITLE
No commands in commandQueue.

### ISSUE THREAD

**Issue by alexfernandez** [Medium/node-bloomd#13]
Using 0.2.1, we are sometimes getting this exception.

```
TypeError: Cannot read property 'error' of undefined
    at BloomClient._onReadable (/home/ubuntu/adserver/node_modules/bloomd/index.js:418:22)
    at ResponseParser.<anonymous> (/home/ubuntu/adserver/node_modules/bloomd/index.js:86:10)
    at ResponseParser.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at ResponseParser.Readable.push (_stream_readable.js:127:10)
    at ResponseParser.Transform.push (_stream_transform.js:140:32)
    at ResponseParser._transform (/home/ubuntu/adserver/node_modules/bloomd/lib/responseParser.js:100:12)
    at ResponseParser.Transform._read (_stream_transform.js:179:10)
```
In current code it is [here](https://github.com/Medium/node-bloomd/blob/master/index.js#L431). Apparently the `commandQueue` is empty so `commandQueue.shift()` returns `undefined`. Shouldn't we check that `command` is truthy?

**Comment by crzidea** [comment]
I've got exactly same issue with this mudule. Any updates?
